name: deploy aliyun

on:
  push:

jobs:
  serverless-devs-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v2
      - run: npm install -g @serverless-devs/s
      - run: s config add --AccessKeyID ${{secrets.AccessKeyID}} --AccessKeySecret ${{secrets.AccessKeySecret}}  --AccountID   ${{secrets.AccountID}}  -a default -f

      -
        name: download latest
        run: |
          downloadUrl=`curl https://api.github.com/repos/cloudreve/Cloudreve/releases/latest | grep -o 'https://github.com/cloudreve/Cloudreve/releases/download.*linux_amd64.tar.gz'`
          wget -q -O cloudreve.tar.gz $downloadUrl
          tar -xvf cloudreve.tar.gz
          # mv cloudreve cr      
          echo "${{ secrets.CR_CONFIG }}" > config.ini   
          
      - run: s deploy