name: deploy azure-web-app

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '1 15 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          n=`date -d "1 day ago" "+%Y-%m-%d"`
          l=`wget -qO- -t1 -T2 "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r ".published_at"`
          if [[ $l =~ $n ]]
          then
               echo "new_release=yes" >> $GITHUB_ENV
          else
               echo "new_release=no" >> $GITHUB_ENV
          fi