name: deploy azure-web-app

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '1 15 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          n=`date -d "1 day ago" "+%Y-%m-%d"`
          l=`wget -qO- -t1 -T2 "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r ".published_at"`
          if [[ $l =~ $n ]]
          then
               echo "new_release=yes" >> $GITHUB_ENV
          else
               echo "new_release=no" >> $GITHUB_ENV
          fi
  work:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ env.new_release == 'yes'  }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v12
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.az
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cr-az:latest